docs: update readme
openedx/xblock-skill-tagging pull request #10
Opened 2023-05-18 04:40 UTC by navinkarkera

**Description:** Updates README.

**JIRA:** `Private-ref`: https://tasks.opencraft.com/browse/BB-7454

**Reviewers:**
- [ ] @sathiscode
- [ ] @sameenfatima78
 
**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2023-05-18 04:40 UTC, openedx-webhooks commented
Thanks for the pull request, @navinkarkera!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-05-18 10:49 UTC, sameenfatima78 approved these changes
Awesome work. This is really helpful!! 🤩

2023-05-18 10:49 UTC, sameenfatima78 commented on README.rst
> +XBlock which depends `taxonomy-connector`_ plugin for generating and serving these
nit: depends on* `taxonomy-connector`

2023-05-18 10:49 UTC, sameenfatima78 commented on README.rst
> +   pip install skill_tagging
To install locally we clone a package in src directory and then install from the relevant shell using `pip install -e /edx/src/repo-name`. Can we add this info as well?

2023-05-18 10:49 UTC, sameenfatima78 commented on README.rst
> +   pip install taxonomy-connector
nit: same as above

2023-05-18 10:49 UTC, sameenfatima78 commented on README.rst
> +openedx_event called ``XBLOCK_SKILL_VERIFIED``. This event needs to be consumed
Can we add a link on word 'emit' where it is actually firing the signal in the code?

2023-05-18 10:49 UTC, sameenfatima78 approved these changes
Awesome work. This is really helpful!! 🤩

2023-05-18 13:14 UTC, sathiscode requested changes

2023-05-18 13:14 UTC, sathiscode commented on README.rst
> +   pip install skill_tagging
Can you please add from which folder/location should i run this command?

2023-05-18 13:14 UTC, sathiscode commented on README.rst
> +   pip install taxonomy-connector
Same as above, which location or shell should I execute this command?

2023-05-18 13:14 UTC, sathiscode commented on README.rst
In **developing** section, is it possible to add details on how to debug the code in local machine?

2023-05-19 07:19 UTC, navinkarkera commented on README.rst
> +   pip install skill_tagging
@sathiscode As mentioned in line 31, it is to be installed in `edx-platform`. Generally openedx is run in docker containers locally via devstack or tutor.

2023-05-19 07:22 UTC, navinkarkera commented on README.rst
> +   pip install taxonomy-connector
It is mentioned just above this block, let me know if it is confusing. I can only include the name of the host application which in this case is `course-discovery`.

> Setup `taxonomy-connector` plugin in course-discovery by installing it via pip

2023-05-19 07:28 UTC, navinkarkera commented on README.rst
Local testing and debugging is done via devstack or tutor as this plugin cannot be executed independently. 

- https://edx.readthedocs.io/projects/open-edx-devstack/en/latest/testing_and_debugging.html
- https://docs.tutor.overhang.io/dev.html

I understand that it is bit confusing for someone new to openedx ecosystem, but adding everything here would be difficult.

2023-05-19 07:29 UTC, navinkarkera commented
@sameenfatima78 @sathiscode Addressed your comments, let me know if something is missing.

2023-05-19 10:15 UTC, sameenfatima78 commented
> @sameenfatima78 @sathiscode Addressed your comments, let me know if something is missing.

Looks good to me.

2023-05-21 14:15 UTC, sathiscode commented on README.rst
> +   pip install taxonomy-connector
Sorry, my bad. I didn't go through it properly.

2023-05-21 14:15 UTC, sathiscode approved these changes

2023-05-22 02:59 UTC, navinkarkera commented on README.rst
> +   pip install skill_tagging
Updated `edx-platform` text to a link pointing to the repository.

2023-05-22 03:00 UTC, navinkarkera commented on README.rst
> +   pip install taxonomy-connector
No worries, updated `course-discovery` text to a link pointing to the repository.

2023-06-14 07:05 UTC, navinkarkera commented
@mphilbrick211 @sameenfatima78 Could we find someone with access to merge this request.

2023-06-14 15:50 UTC, mphilbrick211 commented
@openedx/enterprise-markhors - would someone be able to review/merge this PR? Thanks!

2023-06-14 21:37 UTC, sameenfatima78 commented
@mphilbrick211 At this moment, only @ormsbee and @feanil seem to have access to merge commits. This repository doesn't fall into anyone's ownership yet. 

cc: @irfanuddinahmad

2023-06-14 22:01 UTC, mphilbrick211 commented
> @mphilbrick211 At this moment, only @ormsbee and @feanil seem to have access to merge commits. This repository doesn't fall into anyone's ownership yet.
> 
> cc: @irfanuddinahmad

Thank you for clarifying @sameenfatima78!

2023-06-20 20:19 UTC, mphilbrick211 commented
Hi @feanil - any chance you could take a look at this and merge?

2023-06-21 14:00 UTC, feanil reviewed
A couple of small requests then I think this is good to go.

2023-06-21 14:00 UTC, feanil commented on README.rst
> -TODO: How can a new user go about deploying this component? Is it just a few
Since this package is deployed to PyPI, it may still be helpful to note that here and say that it's automated and will happen for any new tags that get pushed to this repository.

2023-06-21 14:00 UTC, feanil commented on README.rst
> -PLACEHOLDER: Start by going through `the documentation`_.  If you need more help see below.
It's better to acknowledge that there is no published documentation than to omit this section all together.

2023-06-21 14:11 UTC, navinkarkera commented on README.rst
> -TODO: How can a new user go about deploying this component? Is it just a few
Done.

2023-06-21 14:11 UTC, navinkarkera commented on README.rst
> -PLACEHOLDER: Start by going through `the documentation`_.  If you need more help see below.
Done.

2023-06-22 14:17 UTC, feanil approved these changes

2023-06-22 14:17 UTC, merged

2023-06-22 14:17 UTC, openedx-webhooks commented
@navinkarkera 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/xblock-skill-tagging&entry.867055334=https://github.com/openedx/xblock-skill-tagging/pull/10&entry.1484655318=https://github.com/navinkarkera&entry.752974735=2023-05-18+04:40&entry.1917517419=2023-06-22+14:17&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->